### ISSUE TITLE
margin lock 点击后，auto 的值被更改

### ISSUE THREAD

**Issue by biubiujch** [Alex-Programmer-Bro/DesignLite#60]
https://github.com/Alex-Programmer-Bro/DesignLite/assets/85322926/81037425-95e8-4790-a5d0-a23132280fb8

**Comment by Alex-Programmer-Bro** [comment]
<img width="744" alt="image" src="https://github.com/Alex-Programmer-Bro/DesignLite/assets/115539090/d0aadaa1-15b9-4aa1-8053-485e0a3c3d3c">

原因在这个 if 的第一个判断里，对四个方向赋值应该要再改一个

**Comment by Alex-Programmer-Bro** [comment]
解锁的时候直接把原来的 value 设置给四个方向了，确实不对

**Comment by Alex-Programmer-Bro** [comment]
这个测试用例还没有覆盖到

**Comment by Alex-Programmer-Bro** [comment]
@biubiujch

**Comment by Alex-Programmer-Bro** [comment]
我想过一个功能设计，但还没去做。就是锁定状态下，和未锁定状态，保留各自更新的值
