### ISSUE TITLE
桌面版designer 输入框无法输入

### ISSUE THREAD

**Issue by biubiujch** [Alex-Programmer-Bro/DesignLite#90]
@Alex-Programmer-Bro 这玩意儿要在0.0.4-alpha这个版本解决掉吗？

**Comment by Alex-Programmer-Bro** [comment]
解决掉！！！这个版本的主题就是改 bug，哈哈

**Comment by biubiujch** [comment]
找到了解决办法，已经修好了 [https://github.com/tauri-apps/tauri/discussions/3541](url)
